### ISSUE TITLE
Sensor Calibration

### ISSUE THREAD

**Issue by gw8674** [rstrouse/nodejs-poolController-dashPanel#9]
When I attempt to adjust the Air or Water Sensor Calibration in dashPanel, a pop-up appears "Saving Sensor Calibration" but the pop-up never resolves and the changes do not take effect.  I should note that I just did a git pull this afternoon.

I attempted to determine if this was actually a njs-pC issue or a dashPanel issue by going into njspC-webClient > System Info > Edit, to see what would happen there but could not find where to make that sensor adjustment.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/52094163/94978993-275ec700-04d5-11eb-9578-7fb1ed40b7d4.png">.  
<img width="319" alt="image" src="https://user-images.githubusercontent.com/52094163/94979044-74db3400-04d5-11eb-97f4-095725d1732c.png">

Thanks so much for the awesome client!!

**Comment by rstrouse** [comment]
This has been fixed.  Pull njsPC and dashPanel.  This has to do with some changes in 1.047.  The fix is in njsPC but there are other fixes in dashPanel.

**Comment by rstrouse** [comment]
@gw8674 -- Has this been fixed for you?  If you pull the latest dashPanel you can upload your own background images.

**Comment by gw8674** [comment]
@rstrouse  Just pulled a new update but still can't save Temp calibration. It's doing the same thing (freezes up). Only way to exit the screen, is close the browser. Even performed a Reload Config.
I navigated to Settings > Appearance and clicked the Theme pull-down but don't see where I can upload (but I have to be honest, I don't think I can beat the "Purple" theme). That theme rocks imho.

**Comment by rstrouse** [comment]
Sorry, did you also pull njspc?  The fix was actually made in there so you need to pull both of them.  There have been a number of changes to support the 1.047 firmware.

If you pulled the update your Appearance tab should look like this.  If it does not hard refresh your browser.
![image](https://user-images.githubusercontent.com/47839015/95165562-15915400-0761-11eb-8b92-300c09531b1e.png)

**Comment by gw8674** [comment]
I just tried another git pull (njsPc), but it indicates that I'm "Already up to date.", so I must have the latest.
But I now have the updated Settings > Appearance menu.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/52094163/95269560-7dda4700-07ee-11eb-8a9b-da1353f0c824.png">

For whatever reason, it must have taken some time for the web client to 'catch up" lol....

Appears that the "Saving Sensor Calibration..." issue remains however.
It just freezes and I have to close and reopen the browser to get back to home.

**Comment by gw8674** [comment]
What is the preferred photo resolution when uploading a photo? I'm still experimenting but haven't found the exact resolution so that it fits on the web page correctly.  No big deal but if you happen to know, that would be great. Thanks!

**Comment by rstrouse** [comment]
Hmmm... are you running next njspc or are you running the release?  The release is behind and unfortunately, we are still doing development but a couple of users pushed to have the release deployment as if it were the way things should be done but we are working with the user community because we do not all have the same equipment.  This makes the release very far behind.

**Comment by gw8674** [comment]
I was running next until 6.1 was released. Now I'm running nodejs-poolController

**Comment by gw8674** [comment]
Correct me if I'm wrong, the only way to presently delete an uploaded image (I've been experimenting with different size images lol), from the pull-down is to go into the home/pi/nodejs-poolController-dashPanel/themes/Images folder and delete it from there. Is that correct?  Thanks!

**Comment by rstrouse** [comment]
That is correct.  I haven't worked out how I want to delete them from a UI perspective.  Maybe a trashcan in the dropdown but that gets pretty weird for the selection when you are jabbing at them with sausages.

**Comment by rstrouse** [comment]
Yeah, you will find that everything gets fixed with next and the release will lag behind it.  In this instance, there were a number of items related to the IC firmware drop that will only exist in next until the next push into release.  You can either switch to next or you can wait until next is pushed into release.

**Comment by gw8674** [comment]
@rstrouse .. Okay, thanks... Now I understand the process.  I'll be switching to "Next" today!
Thanks again!!!  👍

**Comment by gw8674** [comment]
Well darn.  I thought that I would try to switch over to "next" without any assistance but I'm afraid that I must confess my "noob" status once again 😁.  I thought that all I had to do was enter git clone nodejs-poolController-next, and I tried several combinations but no luck.

I'm sure there is a bit more to it besides just doing a git clone too. I forgot how we initially did it many months ago.  I think it might have been this...
cd ~/nodejs-poolController-next
node dist/app.js&
cd ~/nodejs-poolControl.dashPanel
node dist/app.js&

or  this?
git clone -b next tagyoureit/nodejs-poolController nodejs-poolController-next

Any help is greatly appreciated of course. Thanks!!!

**Comment by tagyoureit** [comment]
Git allows you to switch between branches so you don't need to re-download or download to a new directory.

1.  To clone the base app: `git clone https://github.com/tagyoureit/nodejs-poolController.git`
2. To list local branches: `git branch`
3. To switch branches: `git checkout xyz`; to checkout next `git checkout next`
4. To pull updates: `git pull`

You can do the same for webClient, but @rstrouse isn't using a `next` branch.  🤷   Best bet is to stay current with njsPC/next and -dashPanel/master.

**Comment by gw8674** [comment]
@tagyoureit 
Thanks much! Makes sense now. I'll stay on `next` for njspC.

Problem solved as far as the "save calibration" freeze issue. Thanks...

But I'm having a heck of a time calibrating the water temp. True readout on the dashPanel is 478 (adjusted value is 150 and displayed Pool Temp is 225). Every time I try to adjust it down, it just stays high. I looked at the Pentair webClient and that true readout is -20 (Adjusted value is 104 and displayed Pool Temp is 31) lol...  Are they by any chance working against one another? The Pentair webClient was never that accurate but was never off by this much. 😃 
Any thoughts on what I might try to attempt to get the H2O temp in the ball park?

**Comment by rstrouse** [comment]
Reload the config. 478 is way above the possible range.  The effective temp range is -20 to 127.  Reloading the config should normalize to the panel.  If you are reading -20 on the OCP that tells me there may be a probe issue.  Check your wiring -20 is probably infinite resistance on the probe.

**Comment by gw8674** [comment]
Thanks... Reloading the config brought things back to reasonable numbers. I probably should get in the habit I assume of reloading the config anytime I pull an update.

I checked the sensor and resistance is good and connections are good.
I played around a lot with the calibrations. I got the numbers on the njspC-dashPanel correct.
<img width="288" alt="image" src="https://user-images.githubusercontent.com/52094163/95619977-4f45b180-0a24-11eb-91c0-5e8b6dc05904.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/52094163/95620028-64224500-0a24-11eb-9452-e2b198244385.png">

I noticed that the Pentair webClient definitely seems to "fight" the njspC-dashPanel when it comes to temps / calibrations. Notice how the Pentair webClient pool temp indication is exactly 100 degrees less than than the indication on the njspC-dP.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/52094163/95620201-a77cb380-0a24-11eb-84e8-f37b8c2fddda.png">
<img width="357" alt="image" src="https://user-images.githubusercontent.com/52094163/95620247-ba8f8380-0a24-11eb-8f4f-da2ea92224da.png">

I can't explain it but no matter, since the njspC-dashPanel is my "go to" UMI 😄 now, I guess I'll just concern myself with those numbers and not worry about the Pentair webClient.
Thanks again for the help and all the work that goes in to this project!!

**Comment by gw8674** [comment]
@rstrouse 
BTW,
Pretty cool that we can upload our own images (although IMHO, I still think that the Purple/Vanishing Edge combo), can't be beat. 😄 Thanks!

<img width="841" alt="image" src="https://user-images.githubusercontent.com/52094163/95621540-bb291980-0a26-11eb-91f0-90d0927d7441.png">

**Comment by rstrouse** [comment]
Are you running the released Pentair firmware 1.047.  If you are not now is the time to upgrade.  This absolutely was a problem in 1.040 if you set the calibration using intellicenter.com or the iOS client.

**Comment by gw8674** [comment]
Remember, I was the culprit 😁, that was running beta 1.047 starting in back in the beginning of June and you were kind enough to make a bunch of changes on my behalf because of that fact (https://github.com/rstrouse/nodejs-poolController-dashPanel/issues/4). But I did a manual update when .047 was publicly released recently as well just to ensure that I got any possible tweaks between the beta and the public release. So, running latest and greatest (.047).

**Comment by rstrouse** [comment]
Do me a favor.  In dashPanel set the temperature equal to the temperature shown in the true readout.  This will normalize the temperature adjustment to zero.  Don't do this in the intellicenter.com app as I managed to get the temp all weirded out by messing around with the temp.  Then look at the temperature in both dashPanel and intellicenter.com to see if these temperatures agree.  Then do you temp adjustments with dashPanel.  There is somthing weird with the intellicenter.com app.

Yeah for some reason I thought I convinced you eventually to downgrade to the current release.  I am pretty sure the beta 1.047 and the release had some differences.  Most notably with the group settings.  When the 1.047 dropped, the code that we used to get the groups to work with the beta wasn't right.  Ultimately, it required some since they moved the data around on the messages.  However, they didn't work right in 1.040 either.  I think they are pretty solid in 1.047.

However, I think there may be another bug with 1.047 where if you turn on a circuit from one control panel then turn it off from another the original control panel will turn it back on again.  I have this craziness going on between my ICP and my WCP (indoor control panel and wireless control panel).  That means you have to hit the button twice.

Funny, but I am working on a fix in njspc that will detect it and send the commands again.

**Comment by gw8674** [comment]
@rstrouse..  Thanks...
Okay,
I set the Adjusted Value on both Air and Water to the True Readout.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/52094163/95635530-84143180-0a41-11eb-9666-41509e7e551d.png">
Showing the same on the Home Page.
<img width="156" alt="image" src="https://user-images.githubusercontent.com/52094163/95635560-9bebb580-0a41-11eb-8e82-f6e9aa6bbd60.png">

I then changed the Air and Water temps in the dashPanel to the correct values (97 and 79 respectively).
Air and water then showed correct on the d.p. Home Page. 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/52094163/95637508-bd02d500-0a46-11eb-8605-eef076677c66.png">

I did not make any sensor calibrations in the Pentair webClient per your instructions.

Here is what is showed in the Pentair webClient.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/52094163/95637605-f76c7200-0a46-11eb-8474-344743bedc4b.png">
Pool Temp is right on and Air Temp is about 7 degrees behind the power curve.

Looks like that zeroing it out as you suggested appears to be the trick to get everything to "settle down" as it were and obtain the desired outcome.

I think I will be leaving those calibration adjustments in the Pentair webClient alone from now on. LOL....

As far as .047, not sure if I forgot to mention to you at the time, that Pentair told me upon my receipt of the .047 beta, that by upgrading to 1.047, it will no longer allow the user to "downgrade" to a previous update i.e. 1.042.

So in true fashion, I decided to see if that was for real.. Sure enough, it would not allow me to downgrade to a previous state. 
It takes you through the normal steps for updating via USB drive (Select firmware File for Update, copying Files to IntelliCenter, loading please wait and Click "OK" to Begin Firmware Installation), but after tapping "OK", it errors out and reads "Installation Failed: Loading Previous firmware Configuration.  Guess they were right LOL....  
Not sure what the reasoning is for that but so be it I guess...

Thanks much!!

**Comment by rstrouse** [comment]
Closing for now but will keep an eye on this.  I think Pentair still has some work on this.  Negative temperatures are still a problem.  Perhaps they think that their equipment isn't suitable for skating rinks.
